FROM node:10.23.1-alpine3.10 as build

WORKDIR /usr/src/app
ENV PATH /usr/src/app/node_modules/.bin:$PATH
COPY ./client/package*.json ./

COPY ./client .

RUN npm install && npm run build

FROM nginx:stable-alpine
COPY --from=build /usr/src/app/build/ /usr/share/nginx/html
# COPY --from=build /usr/src/app/nginx/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]