FROM node

# RUN mkdir /usr/src/app/server
WORKDIR /usr/src/app/client

COPY package.json .
RUN npm install #TODO flag as --production

COPY . .

EXPOSE 3000

CMD ["npm", "start"]

# TODO npm build and nginx proxy