FROM node as build

WORKDIR /usr/src/app/client
ENV PATH /usr/src/app/node_modules/.bin:$PATH
COPY package.json .

COPY . .

RUN npm install --production && npm run build

FROM nginx:stable-alpine
COPY --from=build /usr/src/app/client/build/ /usr/share/nginx/html
COPY --from=build /usr/src/app/client/nginx/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]